pimcoreClass: ""
magentoStoreUrl: ""
magentoAccessToken: ""
magentoStoreViewTranslations: ""
magentoCurrency: ""
productName: "name"
productDescription: "description"
productShortDescription: "shortDescription"
productSku: ""
productPrice: ""
productQuantity: ""
productStatus: "published"
parentProductType: ""
configurableProductTypeValue: ""
simpleProductTypeValue: ""
MagentoProductCategory: ""
magentoConfigurableAttributes: ""
magentoCustomAttributes: ""
